import { join } from 'node:path';

import { getAgentWatchHome } from './paths.js';

/** 生成默认 config.yaml — 对齐产品架构 §3.8 */
export function buildAgentWatchConfigYaml(
  agentId: string,
  userId: string,
  uploadSecret: string,
): string {
  const rulesPath = join(getAgentWatchHome(), 'rules', 'builtin.yaml');
  return [
    '# AgentWatch V0 default configuration',
    `agentId: "${agentId}"`,
    `userId: "${userId}"`,
    'server:',
    '  command: npx',
    '  args:',
    '    - -y',
    '    - "@okx_ai/okx-trade-mcp"',
    '  env:',
    '    OKX_API_KEY: ${OKX_API_KEY}',
    '    OKX_SECRET_KEY: ${OKX_SECRET_KEY}',
    '    OKX_PASSPHRASE: ${OKX_PASSPHRASE}',
    '    OKX_PROJECT_ID: ${OKX_PROJECT_ID}',
    'performance:',
    '  maxDetectionLatencyMs: 50',
    'connection:',
    '  timeoutMs: 30000',
    '  autoRestart: true',
    '  maxRestarts: 3',
    'agentWatch:',
    '  performance:',
    '    maxDetectionLatencyMs: 50',
    '  detection:',
    '    enabled: true',
    '    ruleEngine:',
    '      enabled: true',
    `      rulesPath: ${rulesPath}`,
    '      maxMatchTimeMs: 10',
    '    statisticalEngine:',
    '      enabled: true',
    '      zScoreThreshold: 3',
    '      coldStartMinSamples: 30',
    '      combinedScoreThreshold: 0.7',
    '      maxZScoreThreshold: 4',
    '      markovAnomalyThreshold: 0.7',
    '      markovUnknownRatioThreshold: 0.5',
    '      markovSmoothingAlpha: 0.1',
    '      windowSizeMs: 300000',
    '    decisionRouter:',
    '      enabled: true',
    '      blockThreshold: 0.8',
    '      warnThreshold: 0.5',
    '      ruleWeight: 0.6',
    '      statWeight: 0.4',
    '  logging:',
    '    level: info',
    '    format: json',
    '    output: ~/.agentwatch/log.jsonl',
    '    bufferSize: 100',
    '    mask:',
    '      enabled: true',
    '      level: 1',
    '      sensitiveFields:',
    '        - apiKey',
    '        - secret',
    '        - privateKey',
    '        - password',
    '        - mnemonic',
    '    rotation:',
    '      maxSizeMB: 100',
    '      maxFiles: 7',
    '      compress: true',
    '  proxy:',
    '    injectSecurityMarkers: true',
    '  cloud:',
    '    enabled: true',
    '    endpoint: https://kbjcikgoawxhotwwqtin.supabase.co',
    `    uploadSecret: "${uploadSecret}"`,
    '    apiKey: ${AGENTWATCH_API_KEY}',
    '    batch:',
    '      batchSize: 100',
    '      flushIntervalMs: 5000',
    '      maxRetries: 5',
    '  scenarios:',
    '    baselineDeviation:',
    '      monthlyDecay: false',
    '',
  ].join('\n');
}
